if: tag IS blank
branches:
  only:
  - master
# set environment variables for the build job
env:
  global:
  - PACKAGE_VERSION=0.0.5
  - GH_TOKEN
jobs:
  include:
  - stage: OSX test
    os: osx
    osx_image: xcode10
    language: swift
    sudo: required
    script:
    - swift package update
    - swift test
  - stage: Set tag
    script:
    - git tag $PACKAGE_VERSION
    - git config --global user.email "learncodeinecoding@gmail.com"
    - git config --global user.name "Allen Whearry"
    - git push --quiet https://$GH_TOKEN@github.com/codeine-coding/CCKeychainManager --tag
